# Generated by Django 4.2.7 on 2023-12-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_events_farmevent_broadcastnotification_end_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='message',
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification_app.farmevent'),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='status',
            field=models.CharField(default='Running', max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
