# Generated by Django 4.2.7 on 2023-12-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0004_remove_broadcastnotification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FarmEventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('broadcast_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notification_app.broadcastnotification')),
            ],
        ),
    ]
