# Generated by Django 4.2.7 on 2024-01-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0048_typeferpes_applyferpes_type'),
        ('notification_app', '0005_broadcastnotification_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pine.category'),
        ),
    ]
