# Generated by Django 4.2.7 on 2024-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0007_farmevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(null=True),
        ),
    ]
