# Generated by Django 4.2.5 on 2023-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
