# Generated by Django 4.2.4 on 2023-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_stockhistory_cost_stockhistory_receive_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='receive_cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
