# Generated by Django 4.2.4 on 2023-10-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0011_stockhistory2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory2',
        ),
    ]
