# Generated by Django 4.2.4 on 2023-10-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_alter_itemhistory_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='action',
        ),
    ]
