# Generated by Django 4.2.4 on 2023-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0019_itemhistory_issued_by_itemhistory_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
