# Generated by Django 4.2.4 on 2023-10-18 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
