# Generated by Django 4.2.4 on 2023-11-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_roomrejected_messagerejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerejected',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_rejected', to='chat.roomrejected'),
        ),
    ]
