# Generated by Django 4.2.7 on 2023-12-04 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messagerejected_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_bid_price',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
