# Generated by Django 4.2.7 on 2023-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_start_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='start_bid_price',
            field=models.CharField(max_length=255),
        ),
    ]
