# Generated by Django 4.2.7 on 2023-12-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_linkaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkAddress',
        ),
    ]
