# Generated by Django 4.2.7 on 2023-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_delete_linkaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
