# Generated by Django 4.2.4 on 2023-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PinePrice',
        ),
    ]
