# Generated by Django 4.2.4 on 2023-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0002_alter_crop_price_delete_pineprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
