# Generated by Django 4.2.4 on 2023-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0005_alter_yield_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinevalue',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
