# Generated by Django 4.2.4 on 2023-10-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0006_pinevalue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='yield',
            name='calculated_value',
            field=models.FloatField(null=True),
        ),
    ]
