# Generated by Django 4.2.4 on 2023-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0014_remove_yield_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='plant_date',
            field=models.DateField(null=True),
        ),
    ]
