# Generated by Django 4.2.4 on 2023-10-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0017_workerpays'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpays',
            name='workers',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
