# Generated by Django 4.2.4 on 2023-10-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0018_workerpays_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadPine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_yield', models.PositiveIntegerField(null=True)),
                ('harvest_date', models.DateField(null=True)),
                ('calculated_value', models.FloatField(null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pine.category')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pine.pinevalue')),
            ],
        ),
    ]
