# Generated by Django 4.2.4 on 2023-10-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0020_bad_pine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bad_pine',
            new_name='BadValuePine',
        ),
    ]
