# Generated by Django 4.2.4 on 2023-10-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0021_rename_bad_pine_badvaluepine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badvaluepine',
            old_name='value',
            new_name='value2',
        ),
        migrations.AddField(
            model_name='badvaluepine',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='badpine',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pine.badvaluepine'),
        ),
    ]
