# Generated by Django 4.2.4 on 2023-10-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0022_rename_value_badvaluepine_value2_badvaluepine_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badvaluepine',
            old_name='value2',
            new_name='value',
        ),
    ]
