# Generated by Django 4.2.4 on 2023-10-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0023_rename_value2_badvaluepine_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestOnFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_pest', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pine.category')),
            ],
        ),
    ]
