# Generated by Django 4.2.4 on 2023-10-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0025_harvestedgood_biddingprocess'),
    ]

    operations = [
    ]
