# Generated by Django 4.2.4 on 2023-10-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0026_auto_20231020_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkerPays',
            new_name='OtherExpense',
        ),
    ]
