# Generated by Django 4.2.4 on 2023-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0027_rename_workerpays_otherexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
