# Generated by Django 4.2.4 on 2023-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0028_alter_otherexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='price_per_plant',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='plant_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
