# Generated by Django 4.2.4 on 2023-10-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0029_crop_price_per_plant_alter_crop_plant_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedBad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HarvestedGood',
        ),
    ]
