# Generated by Django 4.2.4 on 2023-10-21 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0030_harvestedbad_delete_harvestedgood'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestedbad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pine.category'),
        ),
    ]
