# Generated by Django 4.2.4 on 2023-10-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0031_harvestedbad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestedbad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
