# Generated by Django 4.2.4 on 2023-10-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0033_rejectedpine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='price',
        ),
    ]
