# Generated by Django 4.2.4 on 2017-10-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0034_remove_crop_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherExpense',
            new_name='WorkersExpense',
        ),
    ]
