# Generated by Django 4.2.4 on 2023-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0035_rename_otherexpense_workersexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersexpense',
            name='workers',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
