# Generated by Django 4.2.4 on 2023-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0036_alter_workersexpense_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersexpense',
            name='days',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
