# Generated by Django 4.2.4 on 2023-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0038_applyferpes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingprocess',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
