# Generated by Django 4.2.4 on 2020-10-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0039_alter_biddingprocess_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersexpense',
            name='price_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
