# Generated by Django 4.2.4 on 2023-10-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0041_startexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startexpense',
            name='total_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
