# Generated by Django 4.2.4 on 2023-10-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0042_alter_startexpense_total_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PestOnFarm',
        ),
    ]
