# Generated by Django 4.2.7 on 2023-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0046_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('start', 'Start'), ('completed', 'Completed')], default='start', max_length=20),
        ),
    ]
