# Generated by Django 4.2.7 on 2017-01-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0047_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFerPes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='applyferpes',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pine.typeferpes'),
        ),
    ]
