# Generated by Django 4.2.7 on 2024-01-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
