# Generated by Django 4.2.7 on 2024-01-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unread_messages',
        ),
    ]
